[tool.black]
line-length = 100
target-version = ["py39", "py310", "py311"]

[tool.ruff]
line-length = 100
exclude = [
    "notebooks/*",
    "tests/*",
]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501"]
