name: Docs

on:
  push:
    branches: [ 'main' ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      - name: Deploy to GitHub Pages
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          mkdocs gh-deploy --force
